#!/bin/bash
# Raspberry Pi Wireless Hotspot Installation Script

    clear

    echo "Updating package lists"
    sudo apt-get -y -qq update
    
    echo "Installing udhcpd and hostapd packages"
    sudo apt-get -y -qq install udhcpd
    wget https://github.com/jenssegers/RTL8188-hostapd/archive/v1.1.tar.gz
    tar -zxvf v1.1.tar.gz
    cd RTL8188-hostapd-1.1/hostapd
    sudo make
    sudo make install
    cd ..
    cd ..

    echo "Configuring DHCP"
    sudo rm -rf /etc/udhcpd.conf
    cp ./config-files/udhcpd.conf /etc/udhcpd.conf
    sudo rm -rf /etc/default/udhcpd
    cp ./config-files/udhcpd /etc/default
    
    echo "Configuring interfaces"
    sudo rm -rf /etc/network/interfaces
    cp ./config-files/interfaces /etc/network
    
    echo "Configuring hostapd"
    sudo rm -rf /etc/hostapd/hostapd.conf 
    cp ./config-files/hostapd.conf /etc/hostapd
    sudo rm -rf /etc/default/hostapd
    cp ./config-files/hostapd /etc/default
    
    echo "Configuring NAT"
    sudo rm -rf /etc/sysctl.conf
    cp ./config-files/sysctl.conf /etc
    
    echo "Configuring rc.local"
    sudo rm -rf /etc/rc.local
    cp ./config-files/rc.local /etc

    echo "Configuring iptables"
    sudo rm -rf /etc/iptables.ipv4.nat 
    cp ./config-files/iptables.ipv4.nat /etc

    touch /var/lib/misc/udhcpd.leases
    
    echo "Initialising DHCP server"
    sudo service udhcpd start
    sudo update-rc.d udhcpd enable

    echo "Initialising access point"
    sudo service hostapd start
    sudo update-rc.d hostapd enable
      
    sudo reboot
